apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Values.pageTitle }}</title>
    </head>
    <body>
      <h1>{{ .Values.pageTitle }}</h1>
      <p>This page is templated from ConfigMap 🎯</p>
    </body>
    </html>

